import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://majlis.createstaging.com/en/speaker-registration/');
  await page.locator('.choices__inner').click();
  await page.getByRole('option', { name: 'Eng' }).click();
  await page.getByRole('textbox', { name: 'Full Name *' }).click();
  await page.getByRole('textbox', { name: 'Full Name *' }).fill('fdfd');
  await page.getByRole('textbox', { name: 'Job Title & Organisation *' }).click();
  await page.getByRole('textbox', { name: 'Job Title & Organisation *' }).fill('fdfd');
  await page.getByRole('textbox', { name: 'Email Address *' }).click();
  await page.getByRole('textbox', { name: 'Email Address *' }).fill('fd@fdf.fd');
  await page.getByRole('textbox', { name: 'Phone Number *' }).click();
  await page.getByRole('textbox', { name: 'Phone Number *' }).fill('3333333333333333');
  await page.getByRole('textbox', { name: 'Please provide one point here related to expertise relevant to the session\'s' }).click();
  await page.getByRole('textbox', { name: 'Please provide one point here related to expertise relevant to the session\'s' }).fill('ddddddddddddd');
  await page.getByRole('textbox', { name: 'Please provide one point here related to educational background. *' }).click();
  await page.getByRole('textbox', { name: 'Please provide one point here related to educational background. *' }).fill('d');
  await page.getByRole('textbox', { name: 'Please provide one point here related to memberships or previous experience. *' }).click();
  await page.getByRole('textbox', { name: 'Please provide one point here related to memberships or previous experience. *' }).fill('d');
  await page.getByRole('textbox', { name: 'Type your message...' }).click();
  await page.getByRole('textbox', { name: 'Type your message...' }).fill('d');
  await page.getByRole('textbox', { name: 'Please provide one point here related to publications or awards. *' }).click();
  await page.getByRole('textbox', { name: 'Please provide one point here related to publications or awards. *' }).fill('d');
  await page.locator('.slider').first().click();
  await page.getByRole('textbox', { name: 'Book Titles *' }).click();
  await page.getByRole('textbox', { name: 'Book Titles *' }).fill('ddd');
  await page.locator('#passportFile').getByRole('list').click();
  await page.getByRole('button', { name: 'Click to upload or drag and drop PNG, JPG or PDF (max. 25mb)' }).setInputFiles('Speaker Form (English and Arabic).pdf');
  await page.getByRole('list').filter({ hasText: /^$/ }).click();
  await page.getByRole('button', { name: 'Click to upload or drag and drop PNG or JPG (max. 25mb)' }).setInputFiles('3891e17b-92ca-484b-add8-c672d0ed1c66-contribute 3.jpeg');
  await page.getByRole('link', { name: 'Next' }).click();
  await page.getByRole('textbox', { name: 'Session Title *' }).click();
  await page.getByRole('textbox', { name: 'Session Title *' }).fill('ddd');
  await page.getByRole('textbox', { name: 'Session Description (100' }).click();
  await page.getByRole('textbox', { name: 'Session Description (100' }).fill('ddd s s s s s s s  s  s s s s ');
  await page.getByRole('textbox', { name: 'Session Description (100' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Session Description (100' }).press('ControlOrMeta+c');
  await page.getByRole('textbox', { name: 'Session Description (100' }).fill('ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ddd s s s s s s s  s  s s s s ');
  await page.getByRole('textbox', { name: '1', exact: true }).click();
  await page.getByRole('textbox', { name: '1', exact: true }).fill('dsd');
  await page.getByRole('textbox', { name: '2' }).click();
  await page.getByRole('textbox', { name: '2' }).fill('dsd');
  await page.getByRole('textbox', { name: '3', exact: true }).click();
  await page.getByRole('textbox', { name: '3', exact: true }).fill('dsdsd');
  await page.getByRole('link', { name: 'Next' }).click();
  await page.locator('label').filter({ hasText: 'No' }).first().click();
  await page.getByRole('textbox', { name: 'Outbound Date *' }).click();
  await page.getByRole('textbox', { name: 'Outbound From *' }).click();
  await page.getByRole('textbox', { name: 'Outbound From *' }).fill('dsds');
  await page.getByRole('textbox', { name: 'Outbound To *' }).click();
  await page.getByRole('textbox', { name: 'Outbound To *' }).fill('dsds');
  await page.locator('.toggle-group.form-style.isfalse > div > .toggle > .switch > .slider').first().click();
  await page.getByRole('textbox', { name: 'Airline *' }).click();
  await page.getByRole('textbox', { name: 'Airline *' }).fill('dsds');
  await page.getByRole('textbox', { name: 'Flight Number *' }).click();
  await page.getByRole('textbox', { name: 'Flight Number *' }).fill('dsds');
  await page.getByRole('textbox', { name: 'Return Date *' }).click();
  await page.getByLabel('May 8,').nth(1).click();
  await page.getByRole('textbox', { name: 'Return Date *' }).fill('08/05/2026');
  await page.getByRole('textbox', { name: 'Return From *' }).click();
  await page.getByRole('textbox', { name: 'Return From *' }).fill('dsds');
  await page.getByRole('textbox', { name: 'Return To *' }).click();
  await page.getByRole('textbox', { name: 'Return To *' }).fill('dsds');
  await page.locator('.toggle-group.form-style.isfalse > div > .toggle > .switch > .slider').click();
  await page.getByRole('textbox', { name: 'I want specific flight *' }).click();
  await page.getByRole('textbox', { name: 'I want specific flight *' }).fill('dsds');
  await page.locator('#departure-flightNumber').click();
  await page.locator('#departure-flightNumber').fill('dsds');
  await page.locator('label').filter({ hasText: 'Yes' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Please specify the' }).click();
  await page.getByRole('textbox', { name: 'Please specify the' }).fill('dsdsds');
  await page.getByRole('list').filter({ hasText: /^$/ }).click();
  await page.locator('#filepond--browser-r977p8g0j').setInputFiles('session_02_1.jpg');
  await page.getByRole('link', { name: 'Next' }).click();
  await page.getByRole('textbox', { name: 'Question' }).click();
  await page.getByRole('textbox', { name: 'Question' }).fill('dsdsd');
  await page.getByRole('textbox', { name: 'Correct Answer' }).click();
  await page.getByRole('textbox', { name: 'Correct Answer' }).fill('dsds');
  await page.getByRole('textbox', { name: 'Wrong Answer(s) (up to 3' }).click();
  await page.getByRole('textbox', { name: 'Wrong Answer(s) (up to 3' }).fill('dsd');
  await page.locator('#wrong-answer-2').click();
  await page.locator('#wrong-answer-2').fill('dsds');
  await page.locator('#wrong-answer-3').click();
  await page.locator('#wrong-answer-3').fill('dsds');
  await page.getByRole('link', { name: 'Add question' }).click();
  await page.locator('#question-2').click();
  await page.locator('#question-2').fill('dsds');
  await page.getByRole('textbox', { name: 'Limited water resources,' }).click();
  await page.getByRole('textbox', { name: 'Limited water resources,' }).fill('ds');
  await page.locator('#questions-2 #wrong-answer-1').click();
  await page.locator('#questions-2 #wrong-answer-1').fill('sds');
  await page.locator('#questions-2 #wrong-answer-2').click();
  await page.locator('#questions-2 #wrong-answer-2').fill('dsd');
  await page.locator('#questions-2 #wrong-answer-3').click();
  await page.locator('#questions-2 #wrong-answer-3').fill('dsds');
  await page.getByRole('link', { name: 'Next' }).click();
  await page.getByRole('link', { name: 'Add Invitee' }).click();
  await page.getByRole('textbox', { name: 'Full Name', exact: true }).click();
  await page.getByRole('textbox', { name: 'Full Name', exact: true }).fill('dsds');
  await page.getByRole('textbox', { name: 'Job Title', exact: true }).click();
  await page.getByRole('textbox', { name: 'Job Title', exact: true }).fill('dsds');
  await page.getByRole('textbox', { name: 'Email Address', exact: true }).click();
  await page.getByRole('textbox', { name: 'Email Address', exact: true }).fill('ds@fd.jj');
  await page.getByRole('textbox', { name: 'Phone Number', exact: true }).click();
  await page.getByRole('textbox', { name: 'Phone Number', exact: true }).fill('3333333333333333');
  await page.getByRole('list').filter({ hasText: /^$/ }).click();
  await page.locator('#filepond--browser-nv0mo442r').setInputFiles('Wisdom Character, Ethics Majlis Session Thumbnail Option 2.jpg');
  await page.getByText('By clicking the box, I').click();
  await page.getByRole('link', { name: 'Submit' }).click();
});